title: Juan Luque's Page
logo: assets/img/cropped_DSC_2860.jpg

description: >
  email: juand1121 at gmail dot com

# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme
google_analytics:
show_downloads: false
theme: jekyll-theme-minimal
