title: Juan Luque
logo: images/pfp.jpg

description: >
  You can reach me via email at `juand1121 at gmail dot com`\n
  [Hobbies](hobbies.md) -- [CV](assets/LuqueJuan_resume.pdf)

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics:
show_downloads: false
theme: jekyll-theme-minimal
