title: JL's page

description: >
  Description in footer lorem impsum.

github_username: jdluque
linkedin_username: jdluque

theme: minima
minima:
  # social_links:
  #   - { platform: github, user_url: "https://github.com/jdluque" }
  #   - { platform: linkedin, user_url: "https:linkedin.com/in/jdluque" }
