title: JL's page
# email: "`juand1121 at gmail dot com`"

description: >
  Description in footer lorem impsum.\n
  email: `juand1121 at gmail dot com`

remote_theme: pages-theme/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# github_username: jdluque
# linkedin_username: jdluque

# minima:
  # social_links:
  #   - { platform: github, user_url: "https://github.com/jdluque" }
  #   - { platform: linkedin, user_url: "https:linkedin.com/in/jdluque" }
