title: JL's page

description: >
  Description in footer lorem impsum.\n
  email: `juand1121 at gmail dot com`

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics:
show_downloads: true
theme: jekyll-theme-minimal
